# config.yaml

# Gemini API Configuration
gemini:
  api_key_env: "GEMINI_API_KEY"
  model: "gemini-1.5-flash-latest" 
  request_delay: 2          
  max_retries: 3
  quota_wait_time: 60

# --- Specific configurations for each detector ---
detectors:
  numerical:
    tolerance_pct: 1 # Allow 1% difference for floating point comparisons
  textual:
    similarity_threshold: 0.70 # Lower threshold to catch more potentially related claims
    confidence_threshold: 0.65 # Minimum AI confidence to report a contradiction
  percentage:
    total_tolerance_pp: 2 # Allow a 2 percentage point deviation from 100%
  timeline:
    overlap_tolerance_days: 0 # How many days events can overlap before being flagged

# System Configuration (to prevent warnings)
system:
  version: "3.0.0"

# Logging
logging:
  level: "INFO"
  api_call_tracking: true